modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "subjects_of_ymir"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
Subjects of Ymir
'''
#logoFile = ""

[[dependencies.subjects_of_ymir]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.subjects_of_ymir]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.subjects_of_ymir]]
modId = "palladium"
mandatory = true
versionRange = "[1.20.1-4.5.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.subjects_of_ymir]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.4,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.subjects_of_ymir]]
modId = "pehkui"
mandatory = true
versionRange = "[3.7.12,)"
ordering = "AFTER"
side = "BOTH"